flowchart TD
 subgraph Presentation_Layer["Presentation Layer (Services & API)"]
        APIC["API Controllers"]
        US["UserService"]
        PS["PlaceService"]
        RS["ReviewService"]
        AS["AmenityService"]
  end
 subgraph Business_Logic_Layer["Business Logic Layer (Models & Facade)"]
        Facade["HBnBFacade"]
        UserModel["User"]
        PlaceModel["Place"]
        ReviewModel["Review"]
        AmenityModel["Amenity"]
  end
 subgraph Persistence_Layer["Persistence Layer (Repositories & DB)"]
        UR["UserRepository"]
        PR["PlaceRepository"]
        RR["ReviewRepository"]
        AR["AmenityRepository"]
        DB[("DatabaseConnector")]
  end
    APIC --> US & PS & RS & AS
    US --> Facade
    PS --> Facade
    RS --> Facade
    AS --> Facade
    Facade --> UserModel & PlaceModel & ReviewModel & AmenityModel
    UserModel --> UR
    PlaceModel --> PR
    ReviewModel --> RR
    AmenityModel --> AR
    UR --> DB
    PR --> DB
    RR --> DB
    AR --> DB